### ISSUE TITLE
Small status bar

### ISSUE THREAD

**Issue by desislavsd** [dubeg/theme-lp#7]
Hi, you have done great job. I find the theme awesome. However I need one little option. The status bar is too big and shiny, it constantly distracts me. I like its color, but please add an option to set its height to the default sublime theme's height, something like 20 - 25px I guess. Also the theme doesn't appear in my theme switcher, I would love to see it in there. Thank you in advance. Wish you all the best.

**Comment by dubeg** [comment]
Sorry for the delay.

I agree. When I made it, it didn't concern me as much, but overtime it felt pretty obnoxious. I rarely used LP though so I didn't think to change the height in it as well..

I'll update it to around the height of the default theme, without a specific setting for it since it's just too big for no reason.

---

As for the theme switcher thingy, what plugin do you use? I use Themr and it works pretty well.

**Comment by desislavsd** [comment]
Thank you for the quick fix! 

I use this plugin [Themes Menu Switcher](https://packagecontrol.io/packages/Themes%20Menu%20Switcher) . However, it's not really important.
